language: node_js

matrix:
  include:
  - node_js: 8
  - node_js: 10
  - node_js: 11
  - node_js: 12

script:
  - npm run build
  - npm run build:tests
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
